version: '3'

services :
  db: 
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SellerApp
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval : 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d

  app:
    container_name: sellerapp
    depends_on: 
      db:
        condition: service_healthy
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000


  
